buffer/thug

- src/DOM/DFT.py
Change the call to _normalize_url to match the updated one in Navigator.py
fixes #111
> _normalize_url no longer exists since HTTP Session support

- doc/source/docker.rst
With this change a startup script is called to start the mongodb server before dropping to the shell.
> Change needed for mongodb start

- doc/source/api.rst
- doc/source/configuration.rst
- doc/source/usage.rst
- src/Analysis/virustotal/VirusTotal.py
- src/Logging/virustotal.default.conf
- src/ThugAPI/ThugAPI.py
- src/ThugAPI/ThugOpts.py
- src/thug.py
Allow users to specify a runtime key for VirusTotal APIs.
This may come handy when using a dockerized Thug version where editing the `virustotal.conf` file prior to each run is difficult.
I also created a `virustotal.default.conf` file that should always be there and that contains the default values for the `scanurl` and `reporturl` options; now, `virustotal.conf` can be used to store non-default values for those variables along with the primary API key. Also, `virustotal.conf` is not mandatory any more, since you could live with `virustotal.default.conf` plus a runtime API key value (e.g. the `--vt-apikey` command line option).
> Add runtime VirusTotal API key in ThugAPI and ThugOpts

- doc/source/api.rst
- doc/source/logging.rst
- doc/source/usage.rst
- src/Logging/modules/MongoDB.py
- src/ThugAPI/ThugAPI.py
- src/ThugAPI/ThugOpts.py
- src/thug.py
Let the user specify the address for the MongoDB database instance at runtime, in "host:port" format. This will override any value from `Logging/logging.conf`, including enabling the module if it was disabled in the configuration file.
This may be handy when using Docker, since using the MongoDB instance inside Docker would result in a loss of all results once the container is shut down.
Merged with the latest upstream changes from buffer/thug@a69c6ea3449fd00c7a4a69c9c80808e149125b2b.
> Adding runtime configuration for MongoDB database address

- doc/source/build.rst
Unfortunately there are three different implementations of `magic` for python:
* python-magic 0.4.6 from pypi
* python-magic 5.x from apt
* filemagic 1.6 from pypi
Thug can use either one of the first two, but the docs were reporting a wrong install command.
> Fixing docs with correct command to install python-magic

- src/DOM/Navigator.py
This small fix allows people to use filemagic >= 1.6 from pypi instead than one of the two python-magic versions.
> Allow usage of filemagic instead of python-magic

- src/DOM/Navigator.py
This fix should always return the real mime type instead of a textual description, that may vary according to the version of magic you're using, the operating system you're on, your locale, etc.
This should make it easier for tools to automatically understand when, for example, the real mime type sent by the server is different from the one it declares in the `content-type` HTTP hader.
This commit includes #132 but if you prefer I can make a new one starting from the current state of your master branch.
> Always return real mime type

- src/DOM/DFT.py
Following segfault occured when django webapp called ThugAPI.run_local:
[2015-09-27 10:35:54] Handling DOM Events: load,mousemove
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff68e23b7 in kill () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff68e23b7 in kill () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x0000000000432870 in ?? ()
#2  0x000000000054bb14 in PyEval_EvalFrameEx ()
#3  0x0000000000575d92 in PyEval_EvalCodeEx ()
#4  0x000000000054c028 in PyEval_EvalFrameEx ()
#5  0x0000000000575d92 in PyEval_EvalCodeEx ()
#6  0x000000000054c028 in PyEval_EvalFrameEx ()
#7  0x0000000000575d92 in PyEval_EvalCodeEx ()
#8  0x0000000000577be2 in ?? ()
#9  0x00000000004d91b6 in PyObject_Call ()
#10 0x000000000054d8a5 in PyEval_EvalFrameEx ()
#11 0x0000000000575d92 in …
> PyV8.JSLocker before DFT._run

- src/ActiveX/modules/MicrosoftXMLHTTP.py
While analyzing some malicious JavaScript files spammed as mail attachments, I discovered that the actual `MSXML2.XMLHTTP` ActiveX control does ignore any whitespaces inserted between the domain name and the URI path.
This patch should work around the problem by using urlparse and urllib to split the URL, decode any url-encoded part and strip whitespaces before reassembling the URL.
> MicrosoftXMLHTTP should ignore whitespaces after the domain

- src/ActiveX/CLSID.py
- src/ActiveX/modules/MicrosoftXMLDOM.py
Found a nasty Nemucod variant that decodes a base64 string to a new document created via the `Msxml2.DOMDocument.3.0` ActiveX control. It then uses `ADODB.Stream` to drop the unpacked code to a local `.js` file, which is then executed via `WScript.Shell.run`.
Needed to add `msxml2.domdocument.3.0` and to implement the `createElement()` method to let Thug run it.
> Implement msxml2.domdocument.3.0 and createElement() method

- src/ActiveX/modules/MicrosoftXMLDOM.py
Now `MicrosoftXMLDOM.createElement()` implements a working Node element with some basic properties.
> Implementing Node elements with nodeType and nodeTypedValue

- src/ActiveX/modules/AdodbStream.py
- src/DOM/Navigator.py
- src/Magic/Magic.py
I implemented `AdodbStream.SaveToFile()`, which now saves the content using the newly modified `ThugLogging.save_file()` API.
I had to reuse the code getting the mime type of a given buffer, so I moved it to a separate module.
> Implementing AdodbStream.SaveToFile

- src/Logging/logging.conf
- src/Logging/logging.conf.default
- src/Logging/modules/MongoDB.py
Use a mongo connection string instead of host and port. 
basic example: mongodb://localhost:27017
This allows for more complex connections including TLS/SSL and authentication. 
Auth example: mongodb://username:password@localhost:27017
https://docs.mongodb.com/v3.0/reference/connection-string/
> use mongo connection string in place of host:port

- src/DOM/DFT.py
PyV8 allows to configure stack size limit.
A new sample was causing a stack overflow.
Increasing the stack size limit solved the stack overflow issue for this sample.
> Increase stack size

- src/ActiveX/ActiveX.py
We've been experimenting with overriding/overloading WScript from JavaScript and run into the issue that window.WScript was re-initialized whenever a new WScript.Shell instance was created. This commit fixes that.
> Prevent WScript reset in window

- .gitignore
- docker/Dockerfile
Dockerfile largely based on @lennyzeltser's work, but adding native support for MongoDB, since it's now possible to specify the address of the MongoDB instance to use by using the `--mongodb-address=<host>:<port>` command line option.
> Adding Dockerfile

- docker/Dockerfile
As suggested by Angelo, the linker seems to have problems finding Libemu.
> Fixing missing libemu when running Thug

- thug/DOM/Personality.py
In Windows, shell variables and folder names are case insensitive.
To mimic this, they are converted to lowercase before performing the lookup.
> Shell variables and special folders are case insensitive

- docker/Dockerfile
- requirements.txt
Fixing #187:
- Adding missing `pkg-config` in the apt requirements;
- Allowing newer `pygraphviz` versions (e.g. installing with `easy_install` gets you `1.4rc1`, but then `pip` tries to overwrite it with `1.3.1` and fails because of the missing `pkg-config`).
Cheers,
Pietro
> Allow newer pygraphviz versions and fix missing pkg-config

- thug/Logging/modules/MongoDB.py
It looks like the sample data gets encoded into base64 before getting thrown into GridFS. A couple of issues I ran into, as a result:
- Unnecessarily increases the size of data getting stored into GridFS.
- GridFS metadata has mismatched md5 from the thug.samples collection md5, because thug.samples is the actual md5 of the sample, while the thugfs.fs.files (metadata) md5 is the base64 encoding of the file.
- Retrieving the file requires decoding. This adds 2 extra steps (encode before put, and decode after get).
I also added an extra metadata key for mimetype (mtype) to make lookups a lot faster. For example, if you wanted to search for a specific mimetype you don't need to search in a different database and collection (thug.samples) to find the ObjectId, before pulling the file. This …
> GridFS - Remove base64 encoding and add mimetype metadata

- docs/source/conf.py
- docs/source/requirements.txt
With this modification, the build for RTD will pass.
It's weird right now but RTD looks for a `requirements.txt` file and install all the modules from that, earlier it was looking for `requirements.txt` file and install all the modules from it, whereas now a dedicated requirements file(blank) is made available for RTD. 
Also in the `admin` section of RTD, we need to provide the path to this file `docs/source/requirements.txt`.
> Modifying config for RTD-docs

- thug/ActiveX/CLSID.py
- thug/ActiveX/modules/WinNTSystemInfo.py
- thug/ActiveX/modules/__init__.py
Some JS samples are currently using the WinNTSystemInfo ActiveX control. It's a quite simple one as it only implements four read-only attributes.
> Implementing WinNTSystemInfo ActiveX

- doc/docker.html
- doc/sources/docker.rst.txt
Previously Docker would start and exit immediately.
> Updates Docs

- thug/Logging/modules/ElasticSearch.py
This fix modifies lines 88 and 89 in ElasticSearch.py to adjust the export functionality to be compatible with ES >= 7.0
Tested with ElasticSearch 7.10.0 
Note: The keyword argument `doc_type` is decrecated in ES 7.0 (see https://elasticsearch-py.readthedocs.io/en/7.10.0/api.html#elasticsearch.Elasticsearch.index) Furthermore the result dict returned from  index()-function, does not contain the key 'created' anymore. (See https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docs-index_.html)
> Modify ElasticSearch export functionality in ElasticSearch.py to be compatible with ES >= 7.0 

- README.rst
- thug/DOM/W3C/HTML/HTMLDocumentCompatibleInfo.py
- thug/Logging/ThugLogging.py
- thug/Logging/modules/JSON.py
- thug/Logging/modules/MongoDB.py
- thug/ThugAPI/IThugAPI.py
There are small typos in:
- README.rst
- thug/DOM/W3C/HTML/HTMLDocumentCompatibleInfo.py
- thug/Logging/ThugLogging.py
- thug/Logging/modules/JSON.py
- thug/Logging/modules/MongoDB.py
- thug/ThugAPI/IThugAPI.py
Fixes:
- Should read `occurred` rather than `occured`.
- Should read `mimicking` rather than `mimicing`.
- Should read `compatibility` rather than `compatibity`.
- Should read `additionally` rather than `additionaly`.
Closes #319
> docs: fix a few simple typos

- setup.py
adds `include_package_data=True` to thug's `setup.py` so that when it's installed with `pip`, the package data (config files etc) is correctly added.
brought up a container, cloned master, ran `pip install .`, verified that thug installed but the config files were not present
switched to this branch, brought up new container, ran `pip install .`, verified that thug config files were added in `/etc/thug`
> include package data for pip installs

- docker/Dockerfile
Reworked the Dockerfile to introduce a builder stage to build all the requirements and the final stage to actually create the image with the least requirements, resulting in a way smaller docker image.
To build, run the command below from within the root folder of thug project:
`DOCKER_BUILDKIT=1 docker build -f docker/Dockerfile . -t thug-python3.11`
Would be good to have a Github Actions to run the docker build and push the image to the docker hub which seems to be last time updated in the late July 2021, meaning something is broken in the current building/pushing automation.
This fix #371
> Refactoring the Dockerfile

- .github/dependabot.yml
You should probably enable _Dependabot_ from _Settings_ panel of your repository:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates
> GitHub actions: Add dependabot.yml to manage requirements updates

- thug/thug.py
- Refactored the `thug.py` main file to port cli from `getopt` to `argparse`
- Replaced the `-Y` arg flag with `-B` for the `proxy-connect-timeout` option since it was clashing with `no-code-logging` one
> Porting thug cli from getopt to argparse
