src/ThugAPI/IThugAPI.py, tools/README.md
Just fixed some typos and made some clearance.
=> Fixed typos and made some clearance

utils/setup-debian7.sh, utils/setup-ubuntu.sh
- add requesocks
- delete duplicate packages
=> Update ubuntu and debian instalation scripts

src/ActiveX/CLSID.py, src/ActiveX/modules/WScriptShell.py
I'm also cleaning up some unnecessary whitespaces (whell, actually `vim` did it for me! ;-) )
Cheers,
Pietro
=> Adding ExpandEnvironmentStrings to WScript.Shell ActiveX

src/requirements.txt
=> Delete graphviz which became obsolete

src/requirements.txt
=> Delete yara due to missing version in pip repo

COPYING, README.md
- See https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
- HTTPS > HTTP
=> Minor fixes in text files

utils/setup-debian7.sh, utils/setup-osx.sh, utils/setup-ubuntu.sh
Fixing path for the libemu repo (the `git.carnivore.it` one is dead) and fixing another typo. Also making the ubuntu script executable.
=> Fixing libemu path

src/ActiveX/CLSID.py, src/ActiveX/modules/WScriptShell.py, src/DOM/MIMEHandler.py
Added some functionality that recent .js samples seem to use.
=> Some improvements on WScript.Shell

docker/Dockerfile
I followed @standa4's advice, but I think it's better to get it right on the first attempt instead of reinstalling it after Thug.
=> Fixing pygraphviz as per #189

thug/ThugAPI/ThugAPI.py
Added new Javascript extension **.jse** for local analysis. There are a lot of spam mails with attachments with **.jse** extension.
=> Added new extension for run local Javascript

.gitignore
Hi,
As i was setting the development environment I noticed that we are not ignoring `.idea` folder generated because of PyCharm IDE.
Thanks
=> To ignore .idea(pycharm-ide) files

thug/Classifier/BaseClassifier.py, thug/DOM/Window.py, thug/ThugAPI/ThugAPI.py
A small PR, replaced the deprecated `warn` method to `warning`.
=> [Logging] warn(Deprecated)<->warning

tests/Logging/test_BaseLogging.py, tests/Logging/test_LoggingModules.py, thug/Logging/BaseLogging.py
Hi,
It was a very new experience writing tests.
I am not sure whether LoggingModules need a test or not, but since we are taking the unit test approach, i thought this would be helpful.
This is ready for review, thank you
=> Adding tests for BaseLogging and LoggingModules

thug/Classifier/BaseClassifier.py, thug/Debugger/Debugger.py, thug/Debugger/Shellcode.py, thug/Logging/BaseLogging.py, thug/Logging/LoggingModules.py, thug/Logging/SampleLogging.py, thug/Logging/ThugLogging.py, thug/Logging/modules/HPFeeds.py, thug/Logging/modules/JSON.py, thug/Logging/modules/MongoDB.py, thug/Plugins/ThugPlugins.py, thug/Plugins/plugins/POST-TestPlugin-999/Handler.py, thug/Plugins/plugins/PRE-TestPlugin-999/Handler.py, thug/ThugAPI/ThugAPI.py, thug/WebTracking/Cookies.py, thug/thug.py, tools/distributed/thugctrl.py, tools/distributed/thugd.py, utils/MongoUtils.py, utils/checkinstall.py
Hi,
Just an attempt to make the imports look more organised.
Should we follow PEP8 guidelines for imports, I will make the necessary changes then
Thanks
=> Beautifying imports

tests/Encoding/test_Encoding.py, thug/Encoding/Encoding.py
Hi,
This PR is incomplete till we figure out a way to test these lines as well https://github.com/buffer/thug/blob/18863bf4b37c27a6b8be3ae4606a9f5fdc292c5a/thug/Encoding/Encoding.py#L38-L42
=> [Tests] Encoding test

.codecov.yml, .travis.yml, tox.ini
Hi,
Finally we have tox integrated with travis.
Also added codecov for code coverage.
=> Tox-travis-codecov

setup.cfg
=> Adding config file

tests/ThugAPI/test_Watchdog.py, thug/ThugAPI/Watchdog.py, tox.ini
=> [Tests] Thugapi Watchdog test

thug/Analysis/awis/awis.conf, thug/Analysis/awis/awis.conf.default, thug/Analysis/awis/awis.py
Not anywhere near complete but there's some code that might be usable.
Uses myawis to setup the connection: https://github.com/ashim888/awis
=> Amazon Web Information Service addition

.gitignore, dev/requirements-dev.txt, tests/Logging/modules/test_ElasticSearch.py, tests/test_files/thug.conf, thug/Logging/modules/ElasticSearch.py
=> [Tests] ElasticSearch

thug/thug.py
Bug introduced by https://github.com/buffer/thug/pull/386
Should solve https://github.com/buffer/thug/issues/397
=> Fix init_log call in thug cli
